blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.com/invite/A6GSnKzazr
    about: You can join the discussions on Discord.
  - name: Twitter
    url: https://x.com/getplura
    about: You can follow us on Twitter.
