blank_issues_enabled: true
contact_links:
  - name: Open a blank issue
    url: https://github.com/SkidGod4444/plura/issues/new
    about: Please open a blank issue to if you don't see your issue type here.
  - name: Discord
    url: https://discord.com/invite/A6GSnKzazr
    about: You can join the discussions on Discord.
  - name: Twitter
    url: https://x.com/getplura
    about: You can follow us on Twitter.
