name: Deploy Triggers

on:
  push:
    branches:
      - main
    paths:
      - 'apps/triggers/src'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Set up pnpm environment
        run: |
          pnpm setup
          export PATH=$(pnpm env get-path):$PATH
        shell: bash

      - name: Install dependencies
        run: pnpm install

      - name: 🚀 Deploy Triggers
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        run: |
          pnpm dlx trigger.dev@latest deploy
